### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by andbass** [Chris-Coraggio/Roche#1]
ur code is bad.

plese delate all.

**Comment by Chris-Coraggio** [comment]
@andbass You are entirely correct. Thanks for bringing this to my attention. I will include not bad code in V2.

**Comment by andbass** [comment]
i hv ritten softwarez for ovr 30 yrs.

u now windows?  Imak that

> This guy is good at programming: John Hopkins - CEO of BizWorks Solutions

if u wis to b3 at mi lvl, u mst use rel lagnuage.  goto [http://www.tutorialspoint.com/cobol/](url) n lern
